---
### Acte 1 sur le localhost :
- name: mise en situation 2
  hosts: local
 #Ping de la machine 
  tasks:
  #J'installe ansible-galaxy collection install community.vmware en prerequis 
      - name: Ajout d'un nouveau groupe de port
        community.vmware.vmware_portgroup:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          cluster_name: Cluster
          switch: vSwitch0
          portgroup: VLAN-akim 
          vlan_id: 8
          state: present
          validate_certs: no
        delegate_to: localhost



#perdu la journée parce que les prerequis n'ont pas était fourni pip...
      - name: Ajouter un Tag dans la catégorie Proprio avec votre prénom.
        vmware_tag:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          tag_name: akim
          validate_certs: no
          state: present
          #Obtenu via le playbook GetTagCategoryinfo.yml avec -vvv
          category_id: "urn:vmomi:InventoryServiceCategory:ae1957ef-839b-468c-ac6a-df722535aeb1:GLOBAL"

      - name: Créer une VM Debian 10 à partir du template fourni 'DebTemplate'(login/mdp:root/root et dawan/dawan)
        vmware_guest:
          cluster: Cluster
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: False
          folder: /vm
          name: Deb-akim
          #power_off indiqué sur le site plus valide remplacé par poweredoff
          state: poweredoff
          template: DebTemplate
          #message d'erreur pas le bon nom  data center par defaut du coup precision du datacenter
          datacenter: Datacenter


      - name: Tagguer la VM avec votre tag
        vmware_tag_manager:
            hostname: '{{ vcenter_hostname }}'
            username: '{{ vcenter_username }}'
            password: '{{ vcenter_password }}'
            validate_certs: no
            tag_names:
              - akim
            object_name: Deb-akim
            object_type: VirtualMachine
            state: add
        delegate_to: localhost
     #permet d'executer la commande shell pour afficher la date       
      - name: Recuperer la date et la variabiliser en tstamp
        shell: "date +%Y-%m-%d"
        register: tstamp
#recuperation du stdout (resultat de la commande) dans cur_date variable contenant la date

      - name: Set variables
        set_fact:
          cur_date: "{{ tstamp.stdout}}"

      - name: Modifier l'attribut personnalisé DateCreation avec la date du jour (celle du jour de l'exécution du playbook).
        community.vmware.vmware_guest_custom_attributes:
           hostname: "{{ vcenter_hostname }}"
           username: "{{ vcenter_username }}"
           password: "{{ vcenter_password }}"
           validate_certs: no
           name: Deb-akim
           state: present
           attributes:
            - name: DateCreation
              value: "{{ cur_date }}"

      - name: Modifier la version de la debian pour debian 10 
        community.vmware.vmware_guest:
           hostname: "{{ vcenter_hostname }}"
           username: "{{ vcenter_username }}"
           password: "{{ vcenter_password }}"
           validate_certs: no
           name: Deb-akim
           state: present
           guest_id: debian10_64Guest
      - name: Ajouter interface une interface réseau de type VMxNet3 sur le groupe port précédemment créé
        vmware_guest_network:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          datacenter: "{{ datacenter_name }}"
          cluster: Cluster
          gather_network_info: false
          name: Deb-akim
          validate_certs: no
          networks: 
            - device_type: vmxnet3
              name: VLAN-akim
              state: present
      - name: Redimensionner le disque à 5G.
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          name: Deb-akim
          validate_certs: no
          state: present
          disk:
          - size_gb: 5
      - name: Allumer la VM
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: False
          folder: /vm
          name: Deb-akim
          #power_on indiqué sur le site plus valide remplacé par poweredon
          state: poweredon