---
### Acte 1 sur le localhost :
- name: mise en situation 2
  hosts: local
 #Ping de la machine 
  tasks:
  #J'installe ansible-galaxy collection install community.vmware en prerequis 
      - name: Ajout d'un nouveau groupe de port
        community.vmware.vmware_portgroup:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          cluster_name: Cluster
          switch: vSwitch0
          portgroup: VLAN-akim 
          vlan_id: 8
          state: present
          validate_certs: no
        delegate_to: localhost




      - name: Ajouter un Tag dans la catégorie Proprio avec votre prénom.
        vmware_tag:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          tag_name: akim
          validate_certs: no
          state: present
      